// Code generated by mockery v2.53.6. DO NOT EDIT.

package orm

import (
	context "context"

	database "github.com/goravel/framework/contracts/database"
	mock "github.com/stretchr/testify/mock"

	orm "github.com/goravel/framework/contracts/database/orm"

	sql "database/sql"
)

// MockOrm is an autogenerated mock type for the Orm type
type MockOrm struct {
	mock.Mock
}

type MockOrm_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrm) EXPECT() *MockOrm_Expecter {
	return &MockOrm_Expecter{mock: &_m.Mock}
}

// Config provides a mock function with no fields
func (_m *MockOrm) Config() database.Config {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 database.Config
	if rf, ok := ret.Get(0).(func() database.Config); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(database.Config)
	}

	return r0
}

// MockOrm_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockOrm_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockOrm_Expecter) Config() *MockOrm_Config_Call {
	return &MockOrm_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockOrm_Config_Call) Run(run func()) *MockOrm_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrm_Config_Call) Return(_a0 database.Config) *MockOrm_Config_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrm_Config_Call) RunAndReturn(run func() database.Config) *MockOrm_Config_Call {
	_c.Call.Return(run)
	return _c
}

// Connection provides a mock function with given fields: name
func (_m *MockOrm) Connection(name string) orm.Orm {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Connection")
	}

	var r0 orm.Orm
	if rf, ok := ret.Get(0).(func(string) orm.Orm); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(orm.Orm)
		}
	}

	return r0
}

// MockOrm_Connection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connection'
type MockOrm_Connection_Call struct {
	*mock.Call
}

// Connection is a helper method to define mock.On call
//   - name string
func (_e *MockOrm_Expecter) Connection(name interface{}) *MockOrm_Connection_Call {
	return &MockOrm_Connection_Call{Call: _e.mock.On("Connection", name)}
}

func (_c *MockOrm_Connection_Call) Run(run func(name string)) *MockOrm_Connection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockOrm_Connection_Call) Return(_a0 orm.Orm) *MockOrm_Connection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrm_Connection_Call) RunAndReturn(run func(string) orm.Orm) *MockOrm_Connection_Call {
	_c.Call.Return(run)
	return _c
}

// DB provides a mock function with no fields
func (_m *MockOrm) DB() (*sql.DB, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DB")
	}

	var r0 *sql.DB
	var r1 error
	if rf, ok := ret.Get(0).(func() (*sql.DB, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *sql.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.DB)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrm_DB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DB'
type MockOrm_DB_Call struct {
	*mock.Call
}

// DB is a helper method to define mock.On call
func (_e *MockOrm_Expecter) DB() *MockOrm_DB_Call {
	return &MockOrm_DB_Call{Call: _e.mock.On("DB")}
}

func (_c *MockOrm_DB_Call) Run(run func()) *MockOrm_DB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrm_DB_Call) Return(_a0 *sql.DB, _a1 error) *MockOrm_DB_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrm_DB_Call) RunAndReturn(run func() (*sql.DB, error)) *MockOrm_DB_Call {
	_c.Call.Return(run)
	return _c
}

// DatabaseName provides a mock function with no fields
func (_m *MockOrm) DatabaseName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DatabaseName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockOrm_DatabaseName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DatabaseName'
type MockOrm_DatabaseName_Call struct {
	*mock.Call
}

// DatabaseName is a helper method to define mock.On call
func (_e *MockOrm_Expecter) DatabaseName() *MockOrm_DatabaseName_Call {
	return &MockOrm_DatabaseName_Call{Call: _e.mock.On("DatabaseName")}
}

func (_c *MockOrm_DatabaseName_Call) Run(run func()) *MockOrm_DatabaseName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrm_DatabaseName_Call) Return(_a0 string) *MockOrm_DatabaseName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrm_DatabaseName_Call) RunAndReturn(run func() string) *MockOrm_DatabaseName_Call {
	_c.Call.Return(run)
	return _c
}

// Factory provides a mock function with no fields
func (_m *MockOrm) Factory() orm.Factory {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Factory")
	}

	var r0 orm.Factory
	if rf, ok := ret.Get(0).(func() orm.Factory); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(orm.Factory)
		}
	}

	return r0
}

// MockOrm_Factory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Factory'
type MockOrm_Factory_Call struct {
	*mock.Call
}

// Factory is a helper method to define mock.On call
func (_e *MockOrm_Expecter) Factory() *MockOrm_Factory_Call {
	return &MockOrm_Factory_Call{Call: _e.mock.On("Factory")}
}

func (_c *MockOrm_Factory_Call) Run(run func()) *MockOrm_Factory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrm_Factory_Call) Return(_a0 orm.Factory) *MockOrm_Factory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrm_Factory_Call) RunAndReturn(run func() orm.Factory) *MockOrm_Factory_Call {
	_c.Call.Return(run)
	return _c
}

// Fresh provides a mock function with no fields
func (_m *MockOrm) Fresh() {
	_m.Called()
}

// MockOrm_Fresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fresh'
type MockOrm_Fresh_Call struct {
	*mock.Call
}

// Fresh is a helper method to define mock.On call
func (_e *MockOrm_Expecter) Fresh() *MockOrm_Fresh_Call {
	return &MockOrm_Fresh_Call{Call: _e.mock.On("Fresh")}
}

func (_c *MockOrm_Fresh_Call) Run(run func()) *MockOrm_Fresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrm_Fresh_Call) Return() *MockOrm_Fresh_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockOrm_Fresh_Call) RunAndReturn(run func()) *MockOrm_Fresh_Call {
	_c.Run(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *MockOrm) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockOrm_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockOrm_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockOrm_Expecter) Name() *MockOrm_Name_Call {
	return &MockOrm_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockOrm_Name_Call) Run(run func()) *MockOrm_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrm_Name_Call) Return(_a0 string) *MockOrm_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrm_Name_Call) RunAndReturn(run func() string) *MockOrm_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Observe provides a mock function with given fields: model, observer
func (_m *MockOrm) Observe(model interface{}, observer orm.Observer) {
	_m.Called(model, observer)
}

// MockOrm_Observe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Observe'
type MockOrm_Observe_Call struct {
	*mock.Call
}

// Observe is a helper method to define mock.On call
//   - model interface{}
//   - observer orm.Observer
func (_e *MockOrm_Expecter) Observe(model interface{}, observer interface{}) *MockOrm_Observe_Call {
	return &MockOrm_Observe_Call{Call: _e.mock.On("Observe", model, observer)}
}

func (_c *MockOrm_Observe_Call) Run(run func(model interface{}, observer orm.Observer)) *MockOrm_Observe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}), args[1].(orm.Observer))
	})
	return _c
}

func (_c *MockOrm_Observe_Call) Return() *MockOrm_Observe_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockOrm_Observe_Call) RunAndReturn(run func(interface{}, orm.Observer)) *MockOrm_Observe_Call {
	_c.Run(run)
	return _c
}

// Query provides a mock function with no fields
func (_m *MockOrm) Query() orm.Query {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 orm.Query
	if rf, ok := ret.Get(0).(func() orm.Query); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(orm.Query)
		}
	}

	return r0
}

// MockOrm_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockOrm_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
func (_e *MockOrm_Expecter) Query() *MockOrm_Query_Call {
	return &MockOrm_Query_Call{Call: _e.mock.On("Query")}
}

func (_c *MockOrm_Query_Call) Run(run func()) *MockOrm_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrm_Query_Call) Return(_a0 orm.Query) *MockOrm_Query_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrm_Query_Call) RunAndReturn(run func() orm.Query) *MockOrm_Query_Call {
	_c.Call.Return(run)
	return _c
}

// SetQuery provides a mock function with given fields: query
func (_m *MockOrm) SetQuery(query orm.Query) {
	_m.Called(query)
}

// MockOrm_SetQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetQuery'
type MockOrm_SetQuery_Call struct {
	*mock.Call
}

// SetQuery is a helper method to define mock.On call
//   - query orm.Query
func (_e *MockOrm_Expecter) SetQuery(query interface{}) *MockOrm_SetQuery_Call {
	return &MockOrm_SetQuery_Call{Call: _e.mock.On("SetQuery", query)}
}

func (_c *MockOrm_SetQuery_Call) Run(run func(query orm.Query)) *MockOrm_SetQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(orm.Query))
	})
	return _c
}

func (_c *MockOrm_SetQuery_Call) Return() *MockOrm_SetQuery_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockOrm_SetQuery_Call) RunAndReturn(run func(orm.Query)) *MockOrm_SetQuery_Call {
	_c.Run(run)
	return _c
}

// Transaction provides a mock function with given fields: txFunc
func (_m *MockOrm) Transaction(txFunc func(orm.Query) error) error {
	ret := _m.Called(txFunc)

	if len(ret) == 0 {
		panic("no return value specified for Transaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(func(orm.Query) error) error); ok {
		r0 = rf(txFunc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrm_Transaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transaction'
type MockOrm_Transaction_Call struct {
	*mock.Call
}

// Transaction is a helper method to define mock.On call
//   - txFunc func(orm.Query) error
func (_e *MockOrm_Expecter) Transaction(txFunc interface{}) *MockOrm_Transaction_Call {
	return &MockOrm_Transaction_Call{Call: _e.mock.On("Transaction", txFunc)}
}

func (_c *MockOrm_Transaction_Call) Run(run func(txFunc func(orm.Query) error)) *MockOrm_Transaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(orm.Query) error))
	})
	return _c
}

func (_c *MockOrm_Transaction_Call) Return(_a0 error) *MockOrm_Transaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrm_Transaction_Call) RunAndReturn(run func(func(orm.Query) error) error) *MockOrm_Transaction_Call {
	_c.Call.Return(run)
	return _c
}

// WithContext provides a mock function with given fields: ctx
func (_m *MockOrm) WithContext(ctx context.Context) orm.Orm {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for WithContext")
	}

	var r0 orm.Orm
	if rf, ok := ret.Get(0).(func(context.Context) orm.Orm); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(orm.Orm)
		}
	}

	return r0
}

// MockOrm_WithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithContext'
type MockOrm_WithContext_Call struct {
	*mock.Call
}

// WithContext is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockOrm_Expecter) WithContext(ctx interface{}) *MockOrm_WithContext_Call {
	return &MockOrm_WithContext_Call{Call: _e.mock.On("WithContext", ctx)}
}

func (_c *MockOrm_WithContext_Call) Run(run func(ctx context.Context)) *MockOrm_WithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockOrm_WithContext_Call) Return(_a0 orm.Orm) *MockOrm_WithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrm_WithContext_Call) RunAndReturn(run func(context.Context) orm.Orm) *MockOrm_WithContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrm creates a new instance of MockOrm. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrm(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrm {
	mock := &MockOrm{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
