// Code generated by mockery. DO NOT EDIT.

package notification

import (
	notification "github.com/codedsultan/goravel-notification/contracts"
	mock "github.com/stretchr/testify/mock"
)

// MockChannel is an autogenerated mock type for the Channel type
type MockChannel struct {
	mock.Mock
}

type MockChannel_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChannel) EXPECT() *MockChannel_Expecter {
	return &MockChannel_Expecter{mock: &_m.Mock}
}

// Name provides a mock function with no fields
func (_m *MockChannel) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockChannel_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockChannel_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockChannel_Expecter) Name() *MockChannel_Name_Call {
	return &MockChannel_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockChannel_Name_Call) Run(run func()) *MockChannel_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChannel_Name_Call) Return(_a0 string) *MockChannel_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChannel_Name_Call) RunAndReturn(run func() string) *MockChannel_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: notifiable, _a1
func (_m *MockChannel) Send(notifiable notification.Notifiable, _a1 notification.Notification) error {
	ret := _m.Called(notifiable, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(notification.Notifiable, notification.Notification) error); ok {
		r0 = rf(notifiable, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChannel_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockChannel_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - notifiable notification.Notifiable
//   - _a1 notification.Notification
func (_e *MockChannel_Expecter) Send(notifiable interface{}, _a1 interface{}) *MockChannel_Send_Call {
	return &MockChannel_Send_Call{Call: _e.mock.On("Send", notifiable, _a1)}
}

func (_c *MockChannel_Send_Call) Run(run func(notifiable notification.Notifiable, _a1 notification.Notification)) *MockChannel_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(notification.Notifiable), args[1].(notification.Notification))
	})
	return _c
}

func (_c *MockChannel_Send_Call) Return(_a0 error) *MockChannel_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChannel_Send_Call) RunAndReturn(run func(notification.Notifiable, notification.Notification) error) *MockChannel_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChannel creates a new instance of MockChannel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChannel(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChannel {
	mock := &MockChannel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
