// Code generated by mockery v2.53.5. DO NOT EDIT.
// Regenerate with: go tool mockery --name=Manager --dir=contracts --output=mocks/notification
package notification

import (
	mock "github.com/stretchr/testify/mock"

	contractsnotification "github.com/codedsultan/goravel-notification/contracts"
)

// Manager is an autogenerated mock type for the Manager type.
type Manager struct {
	mock.Mock
}

// NewManager creates a new instance of Manager. It also registers a testing
// interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *Manager {
	mock := &Manager{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}

// Channel provides a mock function with given fields: name
func (m *Manager) Channel(name string) (contractsnotification.Channel, error) {
	_va := []interface{}{name}
	ret := m.Called(_va...)

	var r0 contractsnotification.Channel
	if rf, ok := ret.Get(0).(func(string) contractsnotification.Channel); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(contractsnotification.Channel)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Extend provides a mock function with given fields: channel
func (m *Manager) Extend(channel contractsnotification.Channel) {
	m.Called(channel)
}

// Send provides a mock function with given fields: notifiable, notification
func (m *Manager) Send(
	notifiable contractsnotification.Notifiable,
	notification contractsnotification.Notification,
) error {
	ret := m.Called(notifiable, notification)

	var r0 error
	if rf, ok := ret.Get(0).(func(contractsnotification.Notifiable, contractsnotification.Notification) error); ok {
		r0 = rf(notifiable, notification)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendNow provides a mock function with given fields: notifiable, notification
func (m *Manager) SendNow(
	notifiable contractsnotification.Notifiable,
	notification contractsnotification.Notification,
) error {
	ret := m.Called(notifiable, notification)

	var r0 error
	if rf, ok := ret.Get(0).(func(contractsnotification.Notifiable, contractsnotification.Notification) error); ok {
		r0 = rf(notifiable, notification)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
