// Code generated by mockery. DO NOT EDIT.

package notification

import (
	notification "github.com/codedsultan/goravel-notification/contracts"
	mock "github.com/stretchr/testify/mock"
)

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

// Channel provides a mock function with given fields: name
func (_m *MockManager) Channel(name string) (notification.Channel, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Channel")
	}

	var r0 notification.Channel
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (notification.Channel, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) notification.Channel); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(notification.Channel)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockManager_Channel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Channel'
type MockManager_Channel_Call struct {
	*mock.Call
}

// Channel is a helper method to define mock.On call
//   - name string
func (_e *MockManager_Expecter) Channel(name interface{}) *MockManager_Channel_Call {
	return &MockManager_Channel_Call{Call: _e.mock.On("Channel", name)}
}

func (_c *MockManager_Channel_Call) Run(run func(name string)) *MockManager_Channel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockManager_Channel_Call) Return(_a0 notification.Channel, _a1 error) *MockManager_Channel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockManager_Channel_Call) RunAndReturn(run func(string) (notification.Channel, error)) *MockManager_Channel_Call {
	_c.Call.Return(run)
	return _c
}

// Extend provides a mock function with given fields: channel
func (_m *MockManager) Extend(channel notification.Channel) {
	_m.Called(channel)
}

// MockManager_Extend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Extend'
type MockManager_Extend_Call struct {
	*mock.Call
}

// Extend is a helper method to define mock.On call
//   - channel notification.Channel
func (_e *MockManager_Expecter) Extend(channel interface{}) *MockManager_Extend_Call {
	return &MockManager_Extend_Call{Call: _e.mock.On("Extend", channel)}
}

func (_c *MockManager_Extend_Call) Run(run func(channel notification.Channel)) *MockManager_Extend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(notification.Channel))
	})
	return _c
}

func (_c *MockManager_Extend_Call) Return() *MockManager_Extend_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManager_Extend_Call) RunAndReturn(run func(notification.Channel)) *MockManager_Extend_Call {
	_c.Run(run)
	return _c
}

// Send provides a mock function with given fields: notifiable, _a1
func (_m *MockManager) Send(notifiable notification.Notifiable, _a1 notification.Notification) error {
	ret := _m.Called(notifiable, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(notification.Notifiable, notification.Notification) error); ok {
		r0 = rf(notifiable, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockManager_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockManager_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - notifiable notification.Notifiable
//   - _a1 notification.Notification
func (_e *MockManager_Expecter) Send(notifiable interface{}, _a1 interface{}) *MockManager_Send_Call {
	return &MockManager_Send_Call{Call: _e.mock.On("Send", notifiable, _a1)}
}

func (_c *MockManager_Send_Call) Run(run func(notifiable notification.Notifiable, _a1 notification.Notification)) *MockManager_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(notification.Notifiable), args[1].(notification.Notification))
	})
	return _c
}

func (_c *MockManager_Send_Call) Return(_a0 error) *MockManager_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockManager_Send_Call) RunAndReturn(run func(notification.Notifiable, notification.Notification) error) *MockManager_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendNow provides a mock function with given fields: notifiable, _a1
func (_m *MockManager) SendNow(notifiable notification.Notifiable, _a1 notification.Notification) error {
	ret := _m.Called(notifiable, _a1)

	if len(ret) == 0 {
		panic("no return value specified for SendNow")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(notification.Notifiable, notification.Notification) error); ok {
		r0 = rf(notifiable, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockManager_SendNow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendNow'
type MockManager_SendNow_Call struct {
	*mock.Call
}

// SendNow is a helper method to define mock.On call
//   - notifiable notification.Notifiable
//   - _a1 notification.Notification
func (_e *MockManager_Expecter) SendNow(notifiable interface{}, _a1 interface{}) *MockManager_SendNow_Call {
	return &MockManager_SendNow_Call{Call: _e.mock.On("SendNow", notifiable, _a1)}
}

func (_c *MockManager_SendNow_Call) Run(run func(notifiable notification.Notifiable, _a1 notification.Notification)) *MockManager_SendNow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(notification.Notifiable), args[1].(notification.Notification))
	})
	return _c
}

func (_c *MockManager_SendNow_Call) Return(_a0 error) *MockManager_SendNow_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockManager_SendNow_Call) RunAndReturn(run func(notification.Notifiable, notification.Notification) error) *MockManager_SendNow_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
