// Code generated by mockery. DO NOT EDIT.

package notification

import mock "github.com/stretchr/testify/mock"

// MockNotifiable is an autogenerated mock type for the Notifiable type
type MockNotifiable struct {
	mock.Mock
}

type MockNotifiable_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotifiable) EXPECT() *MockNotifiable_Expecter {
	return &MockNotifiable_Expecter{mock: &_m.Mock}
}

// RouteNotificationFor provides a mock function with given fields: channel
func (_m *MockNotifiable) RouteNotificationFor(channel string) string {
	ret := _m.Called(channel)

	if len(ret) == 0 {
		panic("no return value specified for RouteNotificationFor")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(channel)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockNotifiable_RouteNotificationFor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RouteNotificationFor'
type MockNotifiable_RouteNotificationFor_Call struct {
	*mock.Call
}

// RouteNotificationFor is a helper method to define mock.On call
//   - channel string
func (_e *MockNotifiable_Expecter) RouteNotificationFor(channel interface{}) *MockNotifiable_RouteNotificationFor_Call {
	return &MockNotifiable_RouteNotificationFor_Call{Call: _e.mock.On("RouteNotificationFor", channel)}
}

func (_c *MockNotifiable_RouteNotificationFor_Call) Run(run func(channel string)) *MockNotifiable_RouteNotificationFor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockNotifiable_RouteNotificationFor_Call) Return(_a0 string) *MockNotifiable_RouteNotificationFor_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotifiable_RouteNotificationFor_Call) RunAndReturn(run func(string) string) *MockNotifiable_RouteNotificationFor_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNotifiable creates a new instance of MockNotifiable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotifiable(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotifiable {
	mock := &MockNotifiable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
