// Code generated by mockery v2.53.6. DO NOT EDIT.

package mail

import (
	mail "github.com/goravel/framework/contracts/mail"
	mock "github.com/stretchr/testify/mock"
)

// MockMail is an autogenerated mock type for the Mail type
type MockMail struct {
	mock.Mock
}

type MockMail_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMail) EXPECT() *MockMail_Expecter {
	return &MockMail_Expecter{mock: &_m.Mock}
}

// Attach provides a mock function with given fields: files
func (_m *MockMail) Attach(files []string) mail.Mail {
	ret := _m.Called(files)

	if len(ret) == 0 {
		panic("no return value specified for Attach")
	}

	var r0 mail.Mail
	if rf, ok := ret.Get(0).(func([]string) mail.Mail); ok {
		r0 = rf(files)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mail.Mail)
		}
	}

	return r0
}

// MockMail_Attach_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Attach'
type MockMail_Attach_Call struct {
	*mock.Call
}

// Attach is a helper method to define mock.On call
//   - files []string
func (_e *MockMail_Expecter) Attach(files interface{}) *MockMail_Attach_Call {
	return &MockMail_Attach_Call{Call: _e.mock.On("Attach", files)}
}

func (_c *MockMail_Attach_Call) Run(run func(files []string)) *MockMail_Attach_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string))
	})
	return _c
}

func (_c *MockMail_Attach_Call) Return(_a0 mail.Mail) *MockMail_Attach_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMail_Attach_Call) RunAndReturn(run func([]string) mail.Mail) *MockMail_Attach_Call {
	_c.Call.Return(run)
	return _c
}

// Bcc provides a mock function with given fields: addresses
func (_m *MockMail) Bcc(addresses []string) mail.Mail {
	ret := _m.Called(addresses)

	if len(ret) == 0 {
		panic("no return value specified for Bcc")
	}

	var r0 mail.Mail
	if rf, ok := ret.Get(0).(func([]string) mail.Mail); ok {
		r0 = rf(addresses)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mail.Mail)
		}
	}

	return r0
}

// MockMail_Bcc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Bcc'
type MockMail_Bcc_Call struct {
	*mock.Call
}

// Bcc is a helper method to define mock.On call
//   - addresses []string
func (_e *MockMail_Expecter) Bcc(addresses interface{}) *MockMail_Bcc_Call {
	return &MockMail_Bcc_Call{Call: _e.mock.On("Bcc", addresses)}
}

func (_c *MockMail_Bcc_Call) Run(run func(addresses []string)) *MockMail_Bcc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string))
	})
	return _c
}

func (_c *MockMail_Bcc_Call) Return(_a0 mail.Mail) *MockMail_Bcc_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMail_Bcc_Call) RunAndReturn(run func([]string) mail.Mail) *MockMail_Bcc_Call {
	_c.Call.Return(run)
	return _c
}

// Cc provides a mock function with given fields: addresses
func (_m *MockMail) Cc(addresses []string) mail.Mail {
	ret := _m.Called(addresses)

	if len(ret) == 0 {
		panic("no return value specified for Cc")
	}

	var r0 mail.Mail
	if rf, ok := ret.Get(0).(func([]string) mail.Mail); ok {
		r0 = rf(addresses)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mail.Mail)
		}
	}

	return r0
}

// MockMail_Cc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cc'
type MockMail_Cc_Call struct {
	*mock.Call
}

// Cc is a helper method to define mock.On call
//   - addresses []string
func (_e *MockMail_Expecter) Cc(addresses interface{}) *MockMail_Cc_Call {
	return &MockMail_Cc_Call{Call: _e.mock.On("Cc", addresses)}
}

func (_c *MockMail_Cc_Call) Run(run func(addresses []string)) *MockMail_Cc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string))
	})
	return _c
}

func (_c *MockMail_Cc_Call) Return(_a0 mail.Mail) *MockMail_Cc_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMail_Cc_Call) RunAndReturn(run func([]string) mail.Mail) *MockMail_Cc_Call {
	_c.Call.Return(run)
	return _c
}

// Content provides a mock function with given fields: content
func (_m *MockMail) Content(content mail.Content) mail.Mail {
	ret := _m.Called(content)

	if len(ret) == 0 {
		panic("no return value specified for Content")
	}

	var r0 mail.Mail
	if rf, ok := ret.Get(0).(func(mail.Content) mail.Mail); ok {
		r0 = rf(content)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mail.Mail)
		}
	}

	return r0
}

// MockMail_Content_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Content'
type MockMail_Content_Call struct {
	*mock.Call
}

// Content is a helper method to define mock.On call
//   - content mail.Content
func (_e *MockMail_Expecter) Content(content interface{}) *MockMail_Content_Call {
	return &MockMail_Content_Call{Call: _e.mock.On("Content", content)}
}

func (_c *MockMail_Content_Call) Run(run func(content mail.Content)) *MockMail_Content_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(mail.Content))
	})
	return _c
}

func (_c *MockMail_Content_Call) Return(_a0 mail.Mail) *MockMail_Content_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMail_Content_Call) RunAndReturn(run func(mail.Content) mail.Mail) *MockMail_Content_Call {
	_c.Call.Return(run)
	return _c
}

// From provides a mock function with given fields: address
func (_m *MockMail) From(address mail.Address) mail.Mail {
	ret := _m.Called(address)

	if len(ret) == 0 {
		panic("no return value specified for From")
	}

	var r0 mail.Mail
	if rf, ok := ret.Get(0).(func(mail.Address) mail.Mail); ok {
		r0 = rf(address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mail.Mail)
		}
	}

	return r0
}

// MockMail_From_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'From'
type MockMail_From_Call struct {
	*mock.Call
}

// From is a helper method to define mock.On call
//   - address mail.Address
func (_e *MockMail_Expecter) From(address interface{}) *MockMail_From_Call {
	return &MockMail_From_Call{Call: _e.mock.On("From", address)}
}

func (_c *MockMail_From_Call) Run(run func(address mail.Address)) *MockMail_From_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(mail.Address))
	})
	return _c
}

func (_c *MockMail_From_Call) Return(_a0 mail.Mail) *MockMail_From_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMail_From_Call) RunAndReturn(run func(mail.Address) mail.Mail) *MockMail_From_Call {
	_c.Call.Return(run)
	return _c
}

// Headers provides a mock function with given fields: headers
func (_m *MockMail) Headers(headers map[string]string) mail.Mail {
	ret := _m.Called(headers)

	if len(ret) == 0 {
		panic("no return value specified for Headers")
	}

	var r0 mail.Mail
	if rf, ok := ret.Get(0).(func(map[string]string) mail.Mail); ok {
		r0 = rf(headers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mail.Mail)
		}
	}

	return r0
}

// MockMail_Headers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Headers'
type MockMail_Headers_Call struct {
	*mock.Call
}

// Headers is a helper method to define mock.On call
//   - headers map[string]string
func (_e *MockMail_Expecter) Headers(headers interface{}) *MockMail_Headers_Call {
	return &MockMail_Headers_Call{Call: _e.mock.On("Headers", headers)}
}

func (_c *MockMail_Headers_Call) Run(run func(headers map[string]string)) *MockMail_Headers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[string]string))
	})
	return _c
}

func (_c *MockMail_Headers_Call) Return(_a0 mail.Mail) *MockMail_Headers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMail_Headers_Call) RunAndReturn(run func(map[string]string) mail.Mail) *MockMail_Headers_Call {
	_c.Call.Return(run)
	return _c
}

// Queue provides a mock function with given fields: mailable
func (_m *MockMail) Queue(mailable ...mail.Mailable) error {
	_va := make([]interface{}, len(mailable))
	for _i := range mailable {
		_va[_i] = mailable[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Queue")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(...mail.Mailable) error); ok {
		r0 = rf(mailable...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMail_Queue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Queue'
type MockMail_Queue_Call struct {
	*mock.Call
}

// Queue is a helper method to define mock.On call
//   - mailable ...mail.Mailable
func (_e *MockMail_Expecter) Queue(mailable ...interface{}) *MockMail_Queue_Call {
	return &MockMail_Queue_Call{Call: _e.mock.On("Queue",
		append([]interface{}{}, mailable...)...)}
}

func (_c *MockMail_Queue_Call) Run(run func(mailable ...mail.Mailable)) *MockMail_Queue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]mail.Mailable, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(mail.Mailable)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockMail_Queue_Call) Return(_a0 error) *MockMail_Queue_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMail_Queue_Call) RunAndReturn(run func(...mail.Mailable) error) *MockMail_Queue_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: mailable
func (_m *MockMail) Send(mailable ...mail.Mailable) error {
	_va := make([]interface{}, len(mailable))
	for _i := range mailable {
		_va[_i] = mailable[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(...mail.Mailable) error); ok {
		r0 = rf(mailable...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMail_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockMail_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - mailable ...mail.Mailable
func (_e *MockMail_Expecter) Send(mailable ...interface{}) *MockMail_Send_Call {
	return &MockMail_Send_Call{Call: _e.mock.On("Send",
		append([]interface{}{}, mailable...)...)}
}

func (_c *MockMail_Send_Call) Run(run func(mailable ...mail.Mailable)) *MockMail_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]mail.Mailable, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(mail.Mailable)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockMail_Send_Call) Return(_a0 error) *MockMail_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMail_Send_Call) RunAndReturn(run func(...mail.Mailable) error) *MockMail_Send_Call {
	_c.Call.Return(run)
	return _c
}

// Subject provides a mock function with given fields: subject
func (_m *MockMail) Subject(subject string) mail.Mail {
	ret := _m.Called(subject)

	if len(ret) == 0 {
		panic("no return value specified for Subject")
	}

	var r0 mail.Mail
	if rf, ok := ret.Get(0).(func(string) mail.Mail); ok {
		r0 = rf(subject)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mail.Mail)
		}
	}

	return r0
}

// MockMail_Subject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subject'
type MockMail_Subject_Call struct {
	*mock.Call
}

// Subject is a helper method to define mock.On call
//   - subject string
func (_e *MockMail_Expecter) Subject(subject interface{}) *MockMail_Subject_Call {
	return &MockMail_Subject_Call{Call: _e.mock.On("Subject", subject)}
}

func (_c *MockMail_Subject_Call) Run(run func(subject string)) *MockMail_Subject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockMail_Subject_Call) Return(_a0 mail.Mail) *MockMail_Subject_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMail_Subject_Call) RunAndReturn(run func(string) mail.Mail) *MockMail_Subject_Call {
	_c.Call.Return(run)
	return _c
}

// To provides a mock function with given fields: addresses
func (_m *MockMail) To(addresses []string) mail.Mail {
	ret := _m.Called(addresses)

	if len(ret) == 0 {
		panic("no return value specified for To")
	}

	var r0 mail.Mail
	if rf, ok := ret.Get(0).(func([]string) mail.Mail); ok {
		r0 = rf(addresses)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mail.Mail)
		}
	}

	return r0
}

// MockMail_To_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'To'
type MockMail_To_Call struct {
	*mock.Call
}

// To is a helper method to define mock.On call
//   - addresses []string
func (_e *MockMail_Expecter) To(addresses interface{}) *MockMail_To_Call {
	return &MockMail_To_Call{Call: _e.mock.On("To", addresses)}
}

func (_c *MockMail_To_Call) Run(run func(addresses []string)) *MockMail_To_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string))
	})
	return _c
}

func (_c *MockMail_To_Call) Return(_a0 mail.Mail) *MockMail_To_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMail_To_Call) RunAndReturn(run func([]string) mail.Mail) *MockMail_To_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMail creates a new instance of MockMail. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMail(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMail {
	mock := &MockMail{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
