// Code generated by mockery v2.53.6. DO NOT EDIT.

package log

import (
	context "context"

	http "github.com/goravel/framework/contracts/http"
	log "github.com/goravel/framework/contracts/log"

	mock "github.com/stretchr/testify/mock"
)

// MockLog is an autogenerated mock type for the Log type
type MockLog struct {
	mock.Mock
}

type MockLog_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLog) EXPECT() *MockLog_Expecter {
	return &MockLog_Expecter{mock: &_m.Mock}
}

// Channel provides a mock function with given fields: channel
func (_m *MockLog) Channel(channel string) log.Log {
	ret := _m.Called(channel)

	if len(ret) == 0 {
		panic("no return value specified for Channel")
	}

	var r0 log.Log
	if rf, ok := ret.Get(0).(func(string) log.Log); ok {
		r0 = rf(channel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(log.Log)
		}
	}

	return r0
}

// MockLog_Channel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Channel'
type MockLog_Channel_Call struct {
	*mock.Call
}

// Channel is a helper method to define mock.On call
//   - channel string
func (_e *MockLog_Expecter) Channel(channel interface{}) *MockLog_Channel_Call {
	return &MockLog_Channel_Call{Call: _e.mock.On("Channel", channel)}
}

func (_c *MockLog_Channel_Call) Run(run func(channel string)) *MockLog_Channel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockLog_Channel_Call) Return(_a0 log.Log) *MockLog_Channel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLog_Channel_Call) RunAndReturn(run func(string) log.Log) *MockLog_Channel_Call {
	_c.Call.Return(run)
	return _c
}

// Code provides a mock function with given fields: code
func (_m *MockLog) Code(code string) log.Writer {
	ret := _m.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for Code")
	}

	var r0 log.Writer
	if rf, ok := ret.Get(0).(func(string) log.Writer); ok {
		r0 = rf(code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(log.Writer)
		}
	}

	return r0
}

// MockLog_Code_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Code'
type MockLog_Code_Call struct {
	*mock.Call
}

// Code is a helper method to define mock.On call
//   - code string
func (_e *MockLog_Expecter) Code(code interface{}) *MockLog_Code_Call {
	return &MockLog_Code_Call{Call: _e.mock.On("Code", code)}
}

func (_c *MockLog_Code_Call) Run(run func(code string)) *MockLog_Code_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockLog_Code_Call) Return(_a0 log.Writer) *MockLog_Code_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLog_Code_Call) RunAndReturn(run func(string) log.Writer) *MockLog_Code_Call {
	_c.Call.Return(run)
	return _c
}

// Debug provides a mock function with given fields: args
func (_m *MockLog) Debug(args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLog_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type MockLog_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - args ...interface{}
func (_e *MockLog_Expecter) Debug(args ...interface{}) *MockLog_Debug_Call {
	return &MockLog_Debug_Call{Call: _e.mock.On("Debug",
		append([]interface{}{}, args...)...)}
}

func (_c *MockLog_Debug_Call) Run(run func(args ...interface{})) *MockLog_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockLog_Debug_Call) Return() *MockLog_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLog_Debug_Call) RunAndReturn(run func(...interface{})) *MockLog_Debug_Call {
	_c.Run(run)
	return _c
}

// Debugf provides a mock function with given fields: format, args
func (_m *MockLog) Debugf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLog_Debugf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debugf'
type MockLog_Debugf_Call struct {
	*mock.Call
}

// Debugf is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *MockLog_Expecter) Debugf(format interface{}, args ...interface{}) *MockLog_Debugf_Call {
	return &MockLog_Debugf_Call{Call: _e.mock.On("Debugf",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockLog_Debugf_Call) Run(run func(format string, args ...interface{})) *MockLog_Debugf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLog_Debugf_Call) Return() *MockLog_Debugf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLog_Debugf_Call) RunAndReturn(run func(string, ...interface{})) *MockLog_Debugf_Call {
	_c.Run(run)
	return _c
}

// Error provides a mock function with given fields: args
func (_m *MockLog) Error(args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLog_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockLog_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - args ...interface{}
func (_e *MockLog_Expecter) Error(args ...interface{}) *MockLog_Error_Call {
	return &MockLog_Error_Call{Call: _e.mock.On("Error",
		append([]interface{}{}, args...)...)}
}

func (_c *MockLog_Error_Call) Run(run func(args ...interface{})) *MockLog_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockLog_Error_Call) Return() *MockLog_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLog_Error_Call) RunAndReturn(run func(...interface{})) *MockLog_Error_Call {
	_c.Run(run)
	return _c
}

// Errorf provides a mock function with given fields: format, args
func (_m *MockLog) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLog_Errorf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Errorf'
type MockLog_Errorf_Call struct {
	*mock.Call
}

// Errorf is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *MockLog_Expecter) Errorf(format interface{}, args ...interface{}) *MockLog_Errorf_Call {
	return &MockLog_Errorf_Call{Call: _e.mock.On("Errorf",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockLog_Errorf_Call) Run(run func(format string, args ...interface{})) *MockLog_Errorf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLog_Errorf_Call) Return() *MockLog_Errorf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLog_Errorf_Call) RunAndReturn(run func(string, ...interface{})) *MockLog_Errorf_Call {
	_c.Run(run)
	return _c
}

// Fatal provides a mock function with given fields: args
func (_m *MockLog) Fatal(args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLog_Fatal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fatal'
type MockLog_Fatal_Call struct {
	*mock.Call
}

// Fatal is a helper method to define mock.On call
//   - args ...interface{}
func (_e *MockLog_Expecter) Fatal(args ...interface{}) *MockLog_Fatal_Call {
	return &MockLog_Fatal_Call{Call: _e.mock.On("Fatal",
		append([]interface{}{}, args...)...)}
}

func (_c *MockLog_Fatal_Call) Run(run func(args ...interface{})) *MockLog_Fatal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockLog_Fatal_Call) Return() *MockLog_Fatal_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLog_Fatal_Call) RunAndReturn(run func(...interface{})) *MockLog_Fatal_Call {
	_c.Run(run)
	return _c
}

// Fatalf provides a mock function with given fields: format, args
func (_m *MockLog) Fatalf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLog_Fatalf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fatalf'
type MockLog_Fatalf_Call struct {
	*mock.Call
}

// Fatalf is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *MockLog_Expecter) Fatalf(format interface{}, args ...interface{}) *MockLog_Fatalf_Call {
	return &MockLog_Fatalf_Call{Call: _e.mock.On("Fatalf",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockLog_Fatalf_Call) Run(run func(format string, args ...interface{})) *MockLog_Fatalf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLog_Fatalf_Call) Return() *MockLog_Fatalf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLog_Fatalf_Call) RunAndReturn(run func(string, ...interface{})) *MockLog_Fatalf_Call {
	_c.Run(run)
	return _c
}

// Hint provides a mock function with given fields: hint
func (_m *MockLog) Hint(hint string) log.Writer {
	ret := _m.Called(hint)

	if len(ret) == 0 {
		panic("no return value specified for Hint")
	}

	var r0 log.Writer
	if rf, ok := ret.Get(0).(func(string) log.Writer); ok {
		r0 = rf(hint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(log.Writer)
		}
	}

	return r0
}

// MockLog_Hint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hint'
type MockLog_Hint_Call struct {
	*mock.Call
}

// Hint is a helper method to define mock.On call
//   - hint string
func (_e *MockLog_Expecter) Hint(hint interface{}) *MockLog_Hint_Call {
	return &MockLog_Hint_Call{Call: _e.mock.On("Hint", hint)}
}

func (_c *MockLog_Hint_Call) Run(run func(hint string)) *MockLog_Hint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockLog_Hint_Call) Return(_a0 log.Writer) *MockLog_Hint_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLog_Hint_Call) RunAndReturn(run func(string) log.Writer) *MockLog_Hint_Call {
	_c.Call.Return(run)
	return _c
}

// In provides a mock function with given fields: domain
func (_m *MockLog) In(domain string) log.Writer {
	ret := _m.Called(domain)

	if len(ret) == 0 {
		panic("no return value specified for In")
	}

	var r0 log.Writer
	if rf, ok := ret.Get(0).(func(string) log.Writer); ok {
		r0 = rf(domain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(log.Writer)
		}
	}

	return r0
}

// MockLog_In_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'In'
type MockLog_In_Call struct {
	*mock.Call
}

// In is a helper method to define mock.On call
//   - domain string
func (_e *MockLog_Expecter) In(domain interface{}) *MockLog_In_Call {
	return &MockLog_In_Call{Call: _e.mock.On("In", domain)}
}

func (_c *MockLog_In_Call) Run(run func(domain string)) *MockLog_In_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockLog_In_Call) Return(_a0 log.Writer) *MockLog_In_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLog_In_Call) RunAndReturn(run func(string) log.Writer) *MockLog_In_Call {
	_c.Call.Return(run)
	return _c
}

// Info provides a mock function with given fields: args
func (_m *MockLog) Info(args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLog_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockLog_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - args ...interface{}
func (_e *MockLog_Expecter) Info(args ...interface{}) *MockLog_Info_Call {
	return &MockLog_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{}, args...)...)}
}

func (_c *MockLog_Info_Call) Run(run func(args ...interface{})) *MockLog_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockLog_Info_Call) Return() *MockLog_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLog_Info_Call) RunAndReturn(run func(...interface{})) *MockLog_Info_Call {
	_c.Run(run)
	return _c
}

// Infof provides a mock function with given fields: format, args
func (_m *MockLog) Infof(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLog_Infof_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Infof'
type MockLog_Infof_Call struct {
	*mock.Call
}

// Infof is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *MockLog_Expecter) Infof(format interface{}, args ...interface{}) *MockLog_Infof_Call {
	return &MockLog_Infof_Call{Call: _e.mock.On("Infof",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockLog_Infof_Call) Run(run func(format string, args ...interface{})) *MockLog_Infof_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLog_Infof_Call) Return() *MockLog_Infof_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLog_Infof_Call) RunAndReturn(run func(string, ...interface{})) *MockLog_Infof_Call {
	_c.Run(run)
	return _c
}

// Owner provides a mock function with given fields: owner
func (_m *MockLog) Owner(owner interface{}) log.Writer {
	ret := _m.Called(owner)

	if len(ret) == 0 {
		panic("no return value specified for Owner")
	}

	var r0 log.Writer
	if rf, ok := ret.Get(0).(func(interface{}) log.Writer); ok {
		r0 = rf(owner)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(log.Writer)
		}
	}

	return r0
}

// MockLog_Owner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Owner'
type MockLog_Owner_Call struct {
	*mock.Call
}

// Owner is a helper method to define mock.On call
//   - owner interface{}
func (_e *MockLog_Expecter) Owner(owner interface{}) *MockLog_Owner_Call {
	return &MockLog_Owner_Call{Call: _e.mock.On("Owner", owner)}
}

func (_c *MockLog_Owner_Call) Run(run func(owner interface{})) *MockLog_Owner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockLog_Owner_Call) Return(_a0 log.Writer) *MockLog_Owner_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLog_Owner_Call) RunAndReturn(run func(interface{}) log.Writer) *MockLog_Owner_Call {
	_c.Call.Return(run)
	return _c
}

// Panic provides a mock function with given fields: args
func (_m *MockLog) Panic(args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLog_Panic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Panic'
type MockLog_Panic_Call struct {
	*mock.Call
}

// Panic is a helper method to define mock.On call
//   - args ...interface{}
func (_e *MockLog_Expecter) Panic(args ...interface{}) *MockLog_Panic_Call {
	return &MockLog_Panic_Call{Call: _e.mock.On("Panic",
		append([]interface{}{}, args...)...)}
}

func (_c *MockLog_Panic_Call) Run(run func(args ...interface{})) *MockLog_Panic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockLog_Panic_Call) Return() *MockLog_Panic_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLog_Panic_Call) RunAndReturn(run func(...interface{})) *MockLog_Panic_Call {
	_c.Run(run)
	return _c
}

// Panicf provides a mock function with given fields: format, args
func (_m *MockLog) Panicf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLog_Panicf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Panicf'
type MockLog_Panicf_Call struct {
	*mock.Call
}

// Panicf is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *MockLog_Expecter) Panicf(format interface{}, args ...interface{}) *MockLog_Panicf_Call {
	return &MockLog_Panicf_Call{Call: _e.mock.On("Panicf",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockLog_Panicf_Call) Run(run func(format string, args ...interface{})) *MockLog_Panicf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLog_Panicf_Call) Return() *MockLog_Panicf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLog_Panicf_Call) RunAndReturn(run func(string, ...interface{})) *MockLog_Panicf_Call {
	_c.Run(run)
	return _c
}

// Request provides a mock function with given fields: req
func (_m *MockLog) Request(req http.ContextRequest) log.Writer {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Request")
	}

	var r0 log.Writer
	if rf, ok := ret.Get(0).(func(http.ContextRequest) log.Writer); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(log.Writer)
		}
	}

	return r0
}

// MockLog_Request_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Request'
type MockLog_Request_Call struct {
	*mock.Call
}

// Request is a helper method to define mock.On call
//   - req http.ContextRequest
func (_e *MockLog_Expecter) Request(req interface{}) *MockLog_Request_Call {
	return &MockLog_Request_Call{Call: _e.mock.On("Request", req)}
}

func (_c *MockLog_Request_Call) Run(run func(req http.ContextRequest)) *MockLog_Request_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ContextRequest))
	})
	return _c
}

func (_c *MockLog_Request_Call) Return(_a0 log.Writer) *MockLog_Request_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLog_Request_Call) RunAndReturn(run func(http.ContextRequest) log.Writer) *MockLog_Request_Call {
	_c.Call.Return(run)
	return _c
}

// Response provides a mock function with given fields: res
func (_m *MockLog) Response(res http.ContextResponse) log.Writer {
	ret := _m.Called(res)

	if len(ret) == 0 {
		panic("no return value specified for Response")
	}

	var r0 log.Writer
	if rf, ok := ret.Get(0).(func(http.ContextResponse) log.Writer); ok {
		r0 = rf(res)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(log.Writer)
		}
	}

	return r0
}

// MockLog_Response_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Response'
type MockLog_Response_Call struct {
	*mock.Call
}

// Response is a helper method to define mock.On call
//   - res http.ContextResponse
func (_e *MockLog_Expecter) Response(res interface{}) *MockLog_Response_Call {
	return &MockLog_Response_Call{Call: _e.mock.On("Response", res)}
}

func (_c *MockLog_Response_Call) Run(run func(res http.ContextResponse)) *MockLog_Response_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ContextResponse))
	})
	return _c
}

func (_c *MockLog_Response_Call) Return(_a0 log.Writer) *MockLog_Response_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLog_Response_Call) RunAndReturn(run func(http.ContextResponse) log.Writer) *MockLog_Response_Call {
	_c.Call.Return(run)
	return _c
}

// Stack provides a mock function with given fields: channels
func (_m *MockLog) Stack(channels []string) log.Log {
	ret := _m.Called(channels)

	if len(ret) == 0 {
		panic("no return value specified for Stack")
	}

	var r0 log.Log
	if rf, ok := ret.Get(0).(func([]string) log.Log); ok {
		r0 = rf(channels)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(log.Log)
		}
	}

	return r0
}

// MockLog_Stack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stack'
type MockLog_Stack_Call struct {
	*mock.Call
}

// Stack is a helper method to define mock.On call
//   - channels []string
func (_e *MockLog_Expecter) Stack(channels interface{}) *MockLog_Stack_Call {
	return &MockLog_Stack_Call{Call: _e.mock.On("Stack", channels)}
}

func (_c *MockLog_Stack_Call) Run(run func(channels []string)) *MockLog_Stack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string))
	})
	return _c
}

func (_c *MockLog_Stack_Call) Return(_a0 log.Log) *MockLog_Stack_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLog_Stack_Call) RunAndReturn(run func([]string) log.Log) *MockLog_Stack_Call {
	_c.Call.Return(run)
	return _c
}

// Tags provides a mock function with given fields: tags
func (_m *MockLog) Tags(tags ...string) log.Writer {
	_va := make([]interface{}, len(tags))
	for _i := range tags {
		_va[_i] = tags[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Tags")
	}

	var r0 log.Writer
	if rf, ok := ret.Get(0).(func(...string) log.Writer); ok {
		r0 = rf(tags...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(log.Writer)
		}
	}

	return r0
}

// MockLog_Tags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tags'
type MockLog_Tags_Call struct {
	*mock.Call
}

// Tags is a helper method to define mock.On call
//   - tags ...string
func (_e *MockLog_Expecter) Tags(tags ...interface{}) *MockLog_Tags_Call {
	return &MockLog_Tags_Call{Call: _e.mock.On("Tags",
		append([]interface{}{}, tags...)...)}
}

func (_c *MockLog_Tags_Call) Run(run func(tags ...string)) *MockLog_Tags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockLog_Tags_Call) Return(_a0 log.Writer) *MockLog_Tags_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLog_Tags_Call) RunAndReturn(run func(...string) log.Writer) *MockLog_Tags_Call {
	_c.Call.Return(run)
	return _c
}

// User provides a mock function with given fields: user
func (_m *MockLog) User(user interface{}) log.Writer {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for User")
	}

	var r0 log.Writer
	if rf, ok := ret.Get(0).(func(interface{}) log.Writer); ok {
		r0 = rf(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(log.Writer)
		}
	}

	return r0
}

// MockLog_User_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'User'
type MockLog_User_Call struct {
	*mock.Call
}

// User is a helper method to define mock.On call
//   - user interface{}
func (_e *MockLog_Expecter) User(user interface{}) *MockLog_User_Call {
	return &MockLog_User_Call{Call: _e.mock.On("User", user)}
}

func (_c *MockLog_User_Call) Run(run func(user interface{})) *MockLog_User_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockLog_User_Call) Return(_a0 log.Writer) *MockLog_User_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLog_User_Call) RunAndReturn(run func(interface{}) log.Writer) *MockLog_User_Call {
	_c.Call.Return(run)
	return _c
}

// Warning provides a mock function with given fields: args
func (_m *MockLog) Warning(args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLog_Warning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warning'
type MockLog_Warning_Call struct {
	*mock.Call
}

// Warning is a helper method to define mock.On call
//   - args ...interface{}
func (_e *MockLog_Expecter) Warning(args ...interface{}) *MockLog_Warning_Call {
	return &MockLog_Warning_Call{Call: _e.mock.On("Warning",
		append([]interface{}{}, args...)...)}
}

func (_c *MockLog_Warning_Call) Run(run func(args ...interface{})) *MockLog_Warning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockLog_Warning_Call) Return() *MockLog_Warning_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLog_Warning_Call) RunAndReturn(run func(...interface{})) *MockLog_Warning_Call {
	_c.Run(run)
	return _c
}

// Warningf provides a mock function with given fields: format, args
func (_m *MockLog) Warningf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLog_Warningf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warningf'
type MockLog_Warningf_Call struct {
	*mock.Call
}

// Warningf is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *MockLog_Expecter) Warningf(format interface{}, args ...interface{}) *MockLog_Warningf_Call {
	return &MockLog_Warningf_Call{Call: _e.mock.On("Warningf",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockLog_Warningf_Call) Run(run func(format string, args ...interface{})) *MockLog_Warningf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLog_Warningf_Call) Return() *MockLog_Warningf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLog_Warningf_Call) RunAndReturn(run func(string, ...interface{})) *MockLog_Warningf_Call {
	_c.Run(run)
	return _c
}

// With provides a mock function with given fields: data
func (_m *MockLog) With(data map[string]interface{}) log.Writer {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for With")
	}

	var r0 log.Writer
	if rf, ok := ret.Get(0).(func(map[string]interface{}) log.Writer); ok {
		r0 = rf(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(log.Writer)
		}
	}

	return r0
}

// MockLog_With_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'With'
type MockLog_With_Call struct {
	*mock.Call
}

// With is a helper method to define mock.On call
//   - data map[string]interface{}
func (_e *MockLog_Expecter) With(data interface{}) *MockLog_With_Call {
	return &MockLog_With_Call{Call: _e.mock.On("With", data)}
}

func (_c *MockLog_With_Call) Run(run func(data map[string]interface{})) *MockLog_With_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[string]interface{}))
	})
	return _c
}

func (_c *MockLog_With_Call) Return(_a0 log.Writer) *MockLog_With_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLog_With_Call) RunAndReturn(run func(map[string]interface{}) log.Writer) *MockLog_With_Call {
	_c.Call.Return(run)
	return _c
}

// WithContext provides a mock function with given fields: ctx
func (_m *MockLog) WithContext(ctx context.Context) log.Log {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for WithContext")
	}

	var r0 log.Log
	if rf, ok := ret.Get(0).(func(context.Context) log.Log); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(log.Log)
		}
	}

	return r0
}

// MockLog_WithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithContext'
type MockLog_WithContext_Call struct {
	*mock.Call
}

// WithContext is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLog_Expecter) WithContext(ctx interface{}) *MockLog_WithContext_Call {
	return &MockLog_WithContext_Call{Call: _e.mock.On("WithContext", ctx)}
}

func (_c *MockLog_WithContext_Call) Run(run func(ctx context.Context)) *MockLog_WithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockLog_WithContext_Call) Return(_a0 log.Log) *MockLog_WithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLog_WithContext_Call) RunAndReturn(run func(context.Context) log.Log) *MockLog_WithContext_Call {
	_c.Call.Return(run)
	return _c
}

// WithTrace provides a mock function with no fields
func (_m *MockLog) WithTrace() log.Writer {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for WithTrace")
	}

	var r0 log.Writer
	if rf, ok := ret.Get(0).(func() log.Writer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(log.Writer)
		}
	}

	return r0
}

// MockLog_WithTrace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTrace'
type MockLog_WithTrace_Call struct {
	*mock.Call
}

// WithTrace is a helper method to define mock.On call
func (_e *MockLog_Expecter) WithTrace() *MockLog_WithTrace_Call {
	return &MockLog_WithTrace_Call{Call: _e.mock.On("WithTrace")}
}

func (_c *MockLog_WithTrace_Call) Run(run func()) *MockLog_WithTrace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLog_WithTrace_Call) Return(_a0 log.Writer) *MockLog_WithTrace_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLog_WithTrace_Call) RunAndReturn(run func() log.Writer) *MockLog_WithTrace_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLog creates a new instance of MockLog. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLog(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLog {
	mock := &MockLog{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
